plugins {
    alias(libs.plugins.android.application)
}

// Load the local.properties file
def localProperties = new Properties()
def localPropertiesFile = rootProject.file('local.properties')
if (localPropertiesFile.exists()) {
    localProperties.load(new FileInputStream(localPropertiesFile))
}

android {
    namespace 'com.revise'
    compileSdk {
        version = release(36) {
            minorApiLevel = 1
        }
    }

    defaultConfig {
        applicationId "com.revise"
        minSdk 26
        targetSdk 36
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"

        // Inject the property as a BuildConfig field
        buildConfigField "String", "API_BASE_URL", localProperties.getProperty("API_BASE_URL", "\"http://10.231.229.52:8080/\"")
    }

    buildFeatures {
        // Enable BuildConfig generation
        buildConfig true
    }

    buildTypes {
        release {
            optimization {
                enable false
            }
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }
}

dependencies {
    implementation libs.activity.ktx
    implementation libs.appcompat
    implementation libs.constraintlayout
    implementation libs.material
    testImplementation libs.junit
    androidTestImplementation libs.espresso.core
    androidTestImplementation libs.ext.junit

    // Import Dependencies they we need
    implementation 'androidx.core:core-splashscreen:1.0.1' // import SplashScreen API for set up a highly responsive, modern Splash Screen with full Light and Dark mode support in Java and Android Studio.

    // Jetpack Navigation Component
    def nav_version = "2.7.7"
    implementation "androidx.navigation:navigation-fragment:$nav_version"
    implementation "androidx.navigation:navigation-ui:$nav_version"

    // Retrofit & Gson
    implementation 'com.squareup.retrofit2:retrofit:2.9.0'
    implementation 'com.squareup.retrofit2:converter-gson:2.9.0'

    // Google provides a dedicated library for cryptographic storage.
    implementation "androidx.security:security-crypto:1.1.0-alpha06"
}